services:
  api:
    build:
      context: .
      dockerfile: HospitalAPI/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=postgres; Database=hospital; Username=hospital; Password=admin; Port=5432
      - ASPNETCORE_URLS=http://+:8080
    networks:
      - hospital_net
    depends_on:
      - postgres
  
  
  postgres:
    image: postgres:14-alpine
    ports:
      - '5001:5432'
    environment:
      - POSTGRES_DB=hospital
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=hospital
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hospital_net

networks:
  hospital_net:

volumes:
  postgres_data: